// Code generated by protoc-gen-go.
// source: friends.proto
// DO NOT EDIT!

/*
Package friends is a generated protocol buffer package.

It is generated from these files:
	friends.proto

It has these top-level messages:
	FriendsSetPresenceMessage
	FriendsPresence
	FriendsGetUserAvatarMessage
	FriendsGetUserAvatarResultMessage
	FriendsRosterMessage
	FriendsRequestRoster
*/
package protocol

import proto "../../libs/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FriendsSetPresenceMessage struct {
	Presence         []*FriendsPresence `protobuf:"bytes,1,rep,name=presence" json:"presence,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *FriendsSetPresenceMessage) Reset()         { *m = FriendsSetPresenceMessage{} }
func (m *FriendsSetPresenceMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsSetPresenceMessage) ProtoMessage()    {}

func (m *FriendsSetPresenceMessage) GetPresence() []*FriendsPresence {
	if m != nil {
		return m.Presence
	}
	return nil
}

type FriendsPresence struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendsPresence) Reset()         { *m = FriendsPresence{} }
func (m *FriendsPresence) String() string { return proto.CompactTextString(m) }
func (*FriendsPresence) ProtoMessage()    {}

func (m *FriendsPresence) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *FriendsPresence) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type FriendsGetUserAvatarMessage struct {
	Guid             *int32 `protobuf:"varint,2,req,name=guid" json:"guid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendsGetUserAvatarMessage) Reset()         { *m = FriendsGetUserAvatarMessage{} }
func (m *FriendsGetUserAvatarMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetUserAvatarMessage) ProtoMessage()    {}

func (m *FriendsGetUserAvatarMessage) GetGuid() int32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

type FriendsGetUserAvatarResultMessage struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Guid             *int32 `protobuf:"varint,2,req,name=guid" json:"guid,omitempty"`
	FileData         []byte `protobuf:"bytes,3,req,name=fileData" json:"fileData,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendsGetUserAvatarResultMessage) Reset()         { *m = FriendsGetUserAvatarResultMessage{} }
func (m *FriendsGetUserAvatarResultMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsGetUserAvatarResultMessage) ProtoMessage()    {}

func (m *FriendsGetUserAvatarResultMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *FriendsGetUserAvatarResultMessage) GetGuid() int32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *FriendsGetUserAvatarResultMessage) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

type FriendsRosterMessage struct {
	Result           *int32                                `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	NumResults       *int32                                `protobuf:"varint,2,req,name=numResults" json:"numResults,omitempty"`
	Friends          []*FriendsRosterMessage_FriendDetails `protobuf:"bytes,3,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *FriendsRosterMessage) Reset()         { *m = FriendsRosterMessage{} }
func (m *FriendsRosterMessage) String() string { return proto.CompactTextString(m) }
func (*FriendsRosterMessage) ProtoMessage()    {}

func (m *FriendsRosterMessage) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *FriendsRosterMessage) GetNumResults() int32 {
	if m != nil && m.NumResults != nil {
		return *m.NumResults
	}
	return 0
}

func (m *FriendsRosterMessage) GetFriends() []*FriendsRosterMessage_FriendDetails {
	if m != nil {
		return m.Friends
	}
	return nil
}

type FriendsRosterMessage_FriendDetails struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Isonline         *int32  `protobuf:"varint,3,req,name=isonline" json:"isonline,omitempty"`
	Game             *string `protobuf:"bytes,4,req,name=game" json:"game,omitempty"`
	Hostname         *string `protobuf:"bytes,5,req,name=hostname" json:"hostname,omitempty"`
	CurrentServer    *string `protobuf:"bytes,6,req,name=current_server" json:"current_server,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FriendsRosterMessage_FriendDetails) Reset()         { *m = FriendsRosterMessage_FriendDetails{} }
func (m *FriendsRosterMessage_FriendDetails) String() string { return proto.CompactTextString(m) }
func (*FriendsRosterMessage_FriendDetails) ProtoMessage()    {}

func (m *FriendsRosterMessage_FriendDetails) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *FriendsRosterMessage_FriendDetails) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FriendsRosterMessage_FriendDetails) GetIsonline() int32 {
	if m != nil && m.Isonline != nil {
		return *m.Isonline
	}
	return 0
}

func (m *FriendsRosterMessage_FriendDetails) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *FriendsRosterMessage_FriendDetails) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *FriendsRosterMessage_FriendDetails) GetCurrentServer() string {
	if m != nil && m.CurrentServer != nil {
		return *m.CurrentServer
	}
	return ""
}

type FriendsRequestRoster struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendsRequestRoster) Reset()         { *m = FriendsRequestRoster{} }
func (m *FriendsRequestRoster) String() string { return proto.CompactTextString(m) }
func (*FriendsRequestRoster) ProtoMessage()    {}

func init() {
}
