//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: friends.proto
namespace NPx
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsSetPresenceMessage")]
  public partial class FriendsSetPresenceMessage : global::ProtoBuf.IExtensible
  {
    public FriendsSetPresenceMessage() {}
    
    private readonly global::System.Collections.Generic.List<FriendsPresence> _presence = new global::System.Collections.Generic.List<FriendsPresence>();
    [global::ProtoBuf.ProtoMember(1, Name=@"presence", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendsPresence> presence
    {
      get { return _presence; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsPresence")]
  public partial class FriendsPresence : global::ProtoBuf.IExtensible
  {
    public FriendsPresence() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsGetUserAvatarMessage")]
  public partial class FriendsGetUserAvatarMessage : global::ProtoBuf.IExtensible
  {
    public FriendsGetUserAvatarMessage() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsGetUserAvatarResultMessage")]
  public partial class FriendsGetUserAvatarResultMessage : global::ProtoBuf.IExtensible
  {
    public FriendsGetUserAvatarResultMessage() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private byte[] _fileData;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fileData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] fileData
    {
      get { return _fileData; }
      set { _fileData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsRosterMessage")]
  public partial class FriendsRosterMessage : global::ProtoBuf.IExtensible
  {
    public FriendsRosterMessage() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _numResults;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"numResults", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numResults
    {
      get { return _numResults; }
      set { _numResults = value; }
    }
    private readonly global::System.Collections.Generic.List<FriendsRosterMessage.FriendDetails> _friends = new global::System.Collections.Generic.List<FriendsRosterMessage.FriendDetails>();
    [global::ProtoBuf.ProtoMember(3, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendsRosterMessage.FriendDetails> friends
    {
      get { return _friends; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendDetails")]
  public partial class FriendDetails : global::ProtoBuf.IExtensible
  {
    public FriendDetails() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _isonline;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isonline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isonline
    {
      get { return _isonline; }
      set { _isonline = value; }
    }
    private string _game;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"game", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string game
    {
      get { return _game; }
      set { _game = value; }
    }
    private string _hostname;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hostname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hostname
    {
      get { return _hostname; }
      set { _hostname = value; }
    }
    private string _current_server;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"current_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string current_server
    {
      get { return _current_server; }
      set { _current_server = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsRequestRoster")]
  public partial class FriendsRequestRoster : global::ProtoBuf.IExtensible
  {
    public FriendsRequestRoster() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}